name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create empty data files for build
      run: |
        mkdir -p src/data/cables
        echo '[{"id":"example","name":"Example Landing Point","coordinates":[121.12345,25.56789]}]' > src/data/landing-points.json
        echo '[{"date":"1900-01-01T00:00:00+08:00","status":"disconnected","cableid":"example","segment":"example","title":"Example","description":"Example","reparing_at":"","resolved_at":""}]' > src/data/incidents.json
      
    - name: Run TypeScript check and build
      run: npm run build
      
    # - name: Run linter
    #   run: npm run lint